# Generated by Django 3.2 on 2021-04-14 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='property_type',
            field=models.CharField(choices=[('Land', 'Land'), ('Office', 'Office'), ('House', 'House')], default='House', max_length=10),
        ),
        migrations.AddField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('Rent', 'Rent'), ('Sale', 'Sale')], default='Sale', max_length=10),
        ),
    ]
